apiVersion: app/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: promc
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
        - name: vpromc
          image: memcached
          ports:
            - name: vpromc-port
              containerPort: 11211